-- ============================================================
-- Pacedemy — lộ trình học riêng cho từng em
-- ĐÃ CHẠY trên Supabase ngày 07/10/2026. Giữ lại làm bản ghi,
-- KHÔNG cần chạy lại.
--
-- Ba phần:
--   1. lo_trinh / lo_trinh_tuan / lo_trinh_viec — mẫu cô soạn một lần.
--   2. hoc_vien_lo_trinh — em nào đang theo mẫu nào, từ ngày nào.
--      Tuần 1 tính từ ngày gắn, nên mỗi em một khung ngày riêng dù
--      dùng chung một mẫu.
--   3. viec_rieng — việc cô lồng thêm cho riêng một em, nhắm đúng chỗ
--      em đó hay sai. Nằm ngoài mẫu nên sửa mẫu không làm mất.
--
-- Tiến độ KHÔNG lưu ở đâu cả. lo_trinh_tien_do() đếm lại từ dữ liệu
-- thật trong đúng khung ngày của tuần, nên không có chuyện đánh dấu
-- đã xong cho có. Để trong Postgres vì mỗi tuần phải hỏi vài bảng
-- khác nhau; gọi từ trình duyệt thì tám tuần là hai mươi mấy chuyến.
--
-- lt_deu() đếm số NGÀY có học chứ không đếm số bài: hai em cùng làm
-- 100 câu một tuần, một em rải năm buổi, một em làm dồn một tối, kết
-- quả thi khác hẳn nhau.
--
-- Cả ba hàm đều security definer nên tự kiểm quyền: chỉ giáo viên,
-- hoặc chính em đó, mới xem được.
-- ============================================================

create table if not exists public.lo_trinh (
  id          bigint generated by default as identity primary key,
  ten         text not null,
  mo_ta       text,
  muc_tieu    integer,
  ky_nang     text not null default 'all' check (ky_nang in ('all','listening','reading')),
  so_tuan     integer not null default 4 check (so_tuan between 1 and 52),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.lo_trinh_tuan (
  id          bigint generated by default as identity primary key,
  lo_trinh_id bigint not null references public.lo_trinh(id) on delete cascade,
  tuan        integer not null check (tuan >= 1),
  tieu_de     text not null,
  ghi_chu     text,
  unique (lo_trinh_id, tuan)
);

create table if not exists public.lo_trinh_viec (
  id          bigint generated by default as identity primary key,
  tuan_id     bigint not null references public.lo_trinh_tuan(id) on delete cascade,
  kind        text not null check (kind in ('vocab','part5','listen','read','mock')),
  target      text,
  label       text not null,
  amount      integer not null default 10 check (amount >= 1),
  order_index integer not null default 0
);

-- Một em có thể theo vài lộ trình cùng lúc, ví dụ 650+ chạy nền và
-- một lộ trình chữa Listening ngắn hạn.
create table if not exists public.hoc_vien_lo_trinh (
  id            bigint generated by default as identity primary key,
  student_id    uuid not null references public.profiles(id) on delete cascade,
  lo_trinh_id   bigint not null references public.lo_trinh(id) on delete cascade,
  bat_dau       date not null default current_date,
  buoi_moi_tuan integer not null default 5 check (buoi_moi_tuan between 1 and 7),
  ghi_chu       text,
  is_active     boolean not null default true,
  created_by    uuid,
  created_at    timestamptz not null default now()
);

create index if not exists hv_lo_trinh_sv_idx on public.hoc_vien_lo_trinh (student_id) where is_active;

create table if not exists public.viec_rieng (
  id          bigint generated by default as identity primary key,
  hv_lt_id    bigint not null references public.hoc_vien_lo_trinh(id) on delete cascade,
  tuan        integer not null check (tuan >= 1),
  kind        text not null check (kind in ('vocab','part5','listen','read','mock')),
  target      text,
  label       text not null,
  amount      integer not null default 10 check (amount >= 1),
  ly_do       text,
  created_at  timestamptz not null default now()
);

create index if not exists viec_rieng_hv_idx on public.viec_rieng (hv_lt_id, tuan);

-- Đếm nhanh hơn khi dò theo khung ngày
create index if not exists attempts_user_time_idx on public.attempts (user_id, started_at);
create index if not exists vocab_progress_user_time_idx on public.vocab_progress (user_id, last_reviewed);
create index if not exists mock_tests_user_time_idx on public.mock_tests (user_id, submitted_at);

alter table public.lo_trinh          enable row level security;
alter table public.lo_trinh_tuan     enable row level security;
alter table public.lo_trinh_viec     enable row level security;
alter table public.hoc_vien_lo_trinh enable row level security;
alter table public.viec_rieng        enable row level security;

-- Mẫu lộ trình cho người đã đăng nhập đọc: học viên phải thấy được
-- tuần này mình cần làm gì. Chỉ cô mới sửa.
create policy lo_trinh_doc      on public.lo_trinh      for select using (auth.uid() is not null);
create policy lo_trinh_co       on public.lo_trinh      for all using (is_teacher()) with check (is_teacher());
create policy lo_trinh_tuan_doc on public.lo_trinh_tuan for select using (auth.uid() is not null);
create policy lo_trinh_tuan_co  on public.lo_trinh_tuan for all using (is_teacher()) with check (is_teacher());
create policy lo_trinh_viec_doc on public.lo_trinh_viec for select using (auth.uid() is not null);
create policy lo_trinh_viec_co  on public.lo_trinh_viec for all using (is_teacher()) with check (is_teacher());

create policy hv_lt_doc on public.hoc_vien_lo_trinh for select
  using (auth.uid() = student_id or is_teacher());
create policy hv_lt_co  on public.hoc_vien_lo_trinh for all
  using (is_teacher()) with check (is_teacher());

create policy viec_rieng_doc on public.viec_rieng for select
  using (is_teacher() or exists (
    select 1 from public.hoc_vien_lo_trinh h
    where h.id = viec_rieng.hv_lt_id and h.student_id = auth.uid()));
create policy viec_rieng_co on public.viec_rieng for all
  using (is_teacher()) with check (is_teacher());


-- ============================================================
-- Đếm tiến độ
-- ============================================================

-- Một việc trong lộ trình em đó đã làm được bao nhiêu, trong đúng
-- khung ngày của tuần. Mỗi kiểu việc đếm ở một chỗ khác nhau:
--   vocab  — số từ ôn trong tuần, lấy từ vocab_progress
--   part5  — không chọn dạng thì đếm theo attempts cho nhanh; có chọn
--            dạng thì phải lần xuống từng câu mới biết đúng dạng
--   listen — Part 1 đến 4      read — Part 6, 7      mock — số bài nộp
create or replace function public.lt_dem(
  p_sid uuid, p_kind text, p_target text, p_tu timestamptz, p_den timestamptz
) returns integer
language plpgsql security definer set search_path = public as $$
declare n integer := 0;
begin
  if not (is_teacher() or auth.uid() = p_sid) then
    raise exception 'khong co quyen xem tien do nguoi khac';
  end if;

  if p_kind = 'vocab' then
    select count(distinct p.vocabulary_id) into n
    from vocab_progress p join vocabulary v on v.id = p.vocabulary_id
    where p.user_id = p_sid
      and p.last_reviewed >= p_tu and p.last_reviewed < p_den
      and (p_target is null or p_target = '' or v.topic_id = p_target::bigint);

  elsif p_kind = 'part5' and (p_target is null or p_target = '') then
    select coalesce(sum(a.total_questions), 0) into n
    from attempts a
    where a.user_id = p_sid and a.part = 5
      and a.started_at >= p_tu and a.started_at < p_den;

  elsif p_kind = 'part5' then
    select count(*) into n
    from attempt_answers aa
    join attempts a  on a.id = aa.attempt_id
    join questions q on q.id = aa.question_id
    where a.user_id = p_sid
      and a.started_at >= p_tu and a.started_at < p_den
      and q.part = 5 and q.topic_tag = p_target;

  elsif p_kind in ('listen', 'read') then
    select coalesce(sum(a.total_questions), 0) into n
    from attempts a
    where a.user_id = p_sid
      and a.started_at >= p_tu and a.started_at < p_den
      and (case
             when p_target is null or p_target = ''
               then a.part = any (case when p_kind = 'listen'
                                       then array[1,2,3,4] else array[6,7] end)
             else a.part = p_target::integer
           end);

  elsif p_kind = 'mock' then
    select count(*) into n
    from mock_tests m
    where m.user_id = p_sid and m.submitted_at is not null
      and m.submitted_at >= p_tu and m.submitted_at < p_den;
  end if;

  return coalesce(n, 0);
end $$;

-- Em có học đều không. Đếm số NGÀY khác nhau có hoạt động, chứ không
-- đếm số bài: làm dồn một hôm rồi nghỉ cả tuần thì không gọi là theo
-- lộ trình được.
create or replace function public.lt_deu(p_sid uuid)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare ngay date[]; j jsonb;
begin
  if not (is_teacher() or auth.uid() = p_sid) then
    raise exception 'khong co quyen xem tien do nguoi khac';
  end if;

  select array_agg(distinct d) into ngay from (
    select a.started_at::date d from attempts a
      where a.user_id = p_sid and a.started_at >= current_date - 89
    union
    select p.last_reviewed::date from vocab_progress p
      where p.user_id = p_sid and p.last_reviewed >= current_date - 89
  ) t;

  ngay := coalesce(ngay, array[]::date[]);

  select jsonb_build_object(
    'ngay_7',  (select count(*) from unnest(ngay) x where x >  current_date - 7),
    'ngay_30', (select count(*) from unnest(ngay) x where x >  current_date - 30),
    'ngay_90', (select count(*) from unnest(ngay) x where x >  current_date - 90),
    'hom_nay', (select count(*) > 0 from unnest(ngay) x where x = current_date),
    'gan_nhat',(select max(x) from unnest(ngay) x),
    'tuan', (
      select coalesce(jsonb_agg(jsonb_build_object('tu', tu, 'so_ngay', sn) order by tu), '[]'::jsonb)
      from (
        select (current_date - (w * 7 + 6)) tu,
               (select count(*) from unnest(ngay) x
                 where x >= current_date - (w * 7 + 6) and x <= current_date - (w * 7)) sn
        from generate_series(0, 7) w
      ) q
    )
  ) into j;

  return j;
end $$;

-- Toàn bộ tiến độ một lộ trình của một em: đang ở tuần mấy, từng tuần
-- có việc gì, mỗi việc làm được bao nhiêu trên bao nhiêu.
create or replace function public.lo_trinh_tien_do(p_hv_lt bigint)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  h record; v_tuan_nay integer; ds jsonb := '[]'::jsonb;
  t record; v record; viec jsonb; tu timestamptz; den timestamptz; lam integer;
begin
  select hv.*, lt.ten, lt.mo_ta, lt.so_tuan, lt.muc_tieu, lt.ky_nang
    into h
  from hoc_vien_lo_trinh hv join lo_trinh lt on lt.id = hv.lo_trinh_id
  where hv.id = p_hv_lt;

  if not found then return null; end if;

  if not (is_teacher() or auth.uid() = h.student_id) then
    raise exception 'khong co quyen xem lo trinh nguoi khac';
  end if;

  -- Tuần 1 bắt đầu từ ngày cô giao. Quá số tuần của lộ trình thì dừng
  -- ở tuần cuối, coi như em đang ở chặng cuối chứ không phải đã xong.
  v_tuan_nay := least(h.so_tuan, greatest(1, ((current_date - h.bat_dau) / 7) + 1));

  for t in
    select tuan, tieu_de, ghi_chu from lo_trinh_tuan
    where lo_trinh_id = h.lo_trinh_id order by tuan
  loop
    tu  := (h.bat_dau + (t.tuan - 1) * 7)::timestamptz;
    den := (h.bat_dau + t.tuan * 7)::timestamptz;
    viec := '[]'::jsonb;

    for v in
      select lv.id, lv.kind, lv.target, lv.label, lv.amount, false rieng, null::text ly_do
      from lo_trinh_viec lv
      join lo_trinh_tuan lt2 on lt2.id = lv.tuan_id
      where lt2.lo_trinh_id = h.lo_trinh_id and lt2.tuan = t.tuan
      union all
      select vr.id, vr.kind, vr.target, vr.label, vr.amount, true, vr.ly_do
      from viec_rieng vr
      where vr.hv_lt_id = p_hv_lt and vr.tuan = t.tuan
    loop
      lam := lt_dem(h.student_id, v.kind, v.target, tu, den);
      viec := viec || jsonb_build_object(
        'id', v.id, 'kind', v.kind, 'target', v.target, 'label', v.label,
        'amount', v.amount, 'lam', lam, 'rieng', v.rieng, 'ly_do', v.ly_do);
    end loop;

    ds := ds || jsonb_build_object(
      'tuan', t.tuan, 'tieu_de', t.tieu_de, 'ghi_chu', t.ghi_chu,
      'tu', tu::date, 'den', (den - interval '1 day')::date,
      'viec', viec);
  end loop;

  return jsonb_build_object(
    'id', h.id, 'ten', h.ten, 'mo_ta', h.mo_ta, 'muc_tieu', h.muc_tieu,
    'ky_nang', h.ky_nang, 'so_tuan', h.so_tuan, 'bat_dau', h.bat_dau,
    'buoi_moi_tuan', h.buoi_moi_tuan, 'ghi_chu', h.ghi_chu,
    'student_id', h.student_id, 'tuan_nay', v_tuan_nay,
    'tuan', ds, 'deu', lt_deu(h.student_id));
end $$;

grant execute on function public.lt_dem(uuid, text, text, timestamptz, timestamptz) to authenticated;
grant execute on function public.lt_deu(uuid) to authenticated;
grant execute on function public.lo_trinh_tien_do(bigint) to authenticated;

-- Ba lộ trình mẫu (650+, Cải thiện Listening, Cải thiện Reading) được
-- nạp bằng một khối do $seed$ riêng, có kiểm tên trước khi chèn nên
-- chạy lại cũng không nhân đôi. Nội dung xem trong Teacher Studio →
-- Lộ trình học, sửa thẳng ở đó tiện hơn sửa SQL.
