-- ============================================================
-- Pacedemy — luyện nói và chấm điểm
-- ĐÃ CHẠY trên Supabase ngày 07/10/2026. Giữ lại làm bản ghi,
-- KHÔNG cần chạy lại.
--
-- de_noi   — một tình huống ngắn kèm một cụm từ học viên phải dùng
--            trong câu trả lời. Khác shadowing ở chỗ không có câu
--            mẫu để lặp lại: em phải tự đặt câu, nên mới chấm được
--            ngữ pháp và từ vựng.
-- luot_noi — mỗi lần em nói một đề. Giữ điểm để cô xem em tiến bộ
--            không; KHÔNG giữ file ghi âm, chỉ giữ chữ máy nghe được.
--
-- 20 đề đầu tiên (10 giao tiếp, 10 công sở kiểu TOEIC) nạp bằng một
-- lệnh insert riêng, có kiểm bảng rỗng trước nên chạy lại không nhân
-- đôi. Sửa và thêm đề trong Teacher Studio → Đề luyện nói.
-- ============================================================

create table if not exists public.de_noi (
  id            bigint generated by default as identity primary key,
  kieu          text not null default 'toeic' check (kieu in ('giao-tiep','toeic')),
  tinh_huong    text not null,
  tinh_huong_vi text,
  cum_tu        text not null,
  loai_cum      text,
  phien_am      text,
  nghia_vi      text,
  goi_y         text,
  topic_id      bigint references public.topics(id) on delete set null,
  vocabulary_id bigint references public.vocabulary(id) on delete set null,
  muc_do        smallint not null default 2 check (muc_do between 1 and 3),
  nguon         text not null default 'co' check (nguon in ('co','ai','kho')),
  da_duyet      boolean not null default true,
  is_active     boolean not null default true,
  lan_dung      integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists de_noi_chon_idx on public.de_noi (kieu, muc_do) where is_active and da_duyet;

create table if not exists public.luot_noi (
  id          bigint generated by default as identity primary key,
  student_id  uuid not null references public.profiles(id) on delete cascade,
  de_id       bigint references public.de_noi(id) on delete set null,
  cau_noi     text,
  dung_cum_tu boolean,
  diem_tong   smallint,
  ngu_phap    smallint,
  tu_vung     smallint,
  mach_lac    smallint,
  phat_am     smallint,
  nhan_xet    text,
  cau_goi_y   text,
  chi_tiet    jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists luot_noi_sv_idx on public.luot_noi (student_id, created_at desc);

alter table public.de_noi   enable row level security;
alter table public.luot_noi enable row level security;

-- Học viên chỉ thấy đề đã duyệt và đang bật; cô thấy hết.
create policy de_noi_doc on public.de_noi for select
  using (auth.uid() is not null and ((is_active and da_duyet) or is_teacher()));
create policy de_noi_co  on public.de_noi for all
  using (is_teacher()) with check (is_teacher());

create policy luot_noi_doc on public.luot_noi for select
  using (auth.uid() = student_id or is_teacher());
create policy luot_noi_ghi on public.luot_noi for insert
  with check (auth.uid() = student_id);
create policy luot_noi_co  on public.luot_noi for all
  using (is_teacher()) with check (is_teacher());

-- Đếm lượt dùng của một đề. Qua hàm để học viên không sửa được cột khác.
create or replace function public.de_noi_dem(p_id bigint)
returns void
language sql security definer set search_path = public as $$
  update de_noi set lan_dung = lan_dung + 1 where id = p_id;
$$;

grant execute on function public.de_noi_dem(bigint) to authenticated;
