-- ============================================================
-- Pacedemy — đã chạy trên Supabase ngày 27/09/2026
-- Giữ lại đây làm bản ghi, KHÔNG cần chạy lại.
--
-- Hai việc:
-- 1. Sửa khoá chính bảng exam_questions. Bảng này vốn theo thiết kế cũ
--    (bảng nối exams × questions, khoá ghép exam_id + question_id).
--    Web lại dùng exam_questions.id, cột đó chưa hề tồn tại, nên web
--    không lưu được câu thi thử nào — bảng rỗng hoàn toàn.
-- 2. Thêm cột exam_question_id vào attempt_answers để truy ngược được
--    học viên sai câu nào trong bài thi thử.
--
-- Thời gian mỗi câu dùng cột seconds_spent đã có sẵn, không thêm cột mới.
-- Quyền cho giáo viên đọc bài làm học viên cũng đã có sẵn từ trước.
-- ============================================================

ALTER TABLE public.exam_questions DROP CONSTRAINT IF EXISTS exam_questions_pkey;

ALTER TABLE public.exam_questions
  ALTER COLUMN exam_id     DROP NOT NULL,
  ALTER COLUMN question_id DROP NOT NULL;

ALTER TABLE public.exam_questions
  ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.exam_questions ADD PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS exam_questions_set_idx ON public.exam_questions (exam_set_id);

ALTER TABLE public.attempt_answers
  ADD COLUMN IF NOT EXISTS exam_question_id bigint
  REFERENCES public.exam_questions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS attempt_answers_attempt_idx ON public.attempt_answers (attempt_id);
CREATE INDEX IF NOT EXISTS attempt_answers_exam_q_idx  ON public.attempt_answers (exam_question_id);
